### ISSUE TITLE
Rejeição Codigo 850 Mensagem Data de vencimento da parcela nao informada ou menor que a Data de vencimento da parcela anterior

### ISSUE THREAD

**Issue by pauloneda** [akretion/l10n-brazil#79]
https://github.com/akretion/l10n-brazil/blob/9ffb4bbcf643caeb93c9562fd11829cacbf38742/l10n_br_account_product/sped/nfe/document.py#L73
invoice.move_line_receivable_id é criado com ((line).sorted())

não sei se está correto, mas com o código abaixo ficou correto

 for move_line in (invoice.move_line_receivable_id).sorted(reverse=True):

**Comment by mbcosta** [comment]
ola @pauloneda obrigado pelo retorno, testei seu código em uma NFe com 5 Parcelas

Coloquei um "print('DATA VENCIMENTO', move_line.date_maturity)" logo após o "for", antes da sua alteração o resultado que tive foi esse:

DATA VENCIMENTO 2018-08-23
DATA VENCIMENTO 2018-08-30
DATA VENCIMENTO 2018-09-06
DATA VENCIMENTO 2018-09-13
DATA VENCIMENTO 2018-09-20

O que parece estar certo, ao fazer a alteração que você está sugerindo essa ordem foi invertida e passei a ter o erro "Rejeição Codigo 850 Mensagem Data de vencimento da parcela nao informada ou menor que a Data de vencimento da parcela anterior" . 

Verifique se você tem algum modulo instalado que possa estar invertendo essa ordem no momento da criação( pode ser isso, se for seria bom informar qual modulo é, para poder analisar melhor ) e se na tela de "Vencimentos" na NFe os registros aparecem na sequencia

![image](https://user-images.githubusercontent.com/6341149/43589546-589bf316-9645-11e8-84f5-03b48a7d6caf.png)

**Comment by pauloneda** [comment]
@mbcosta 
Na Minha Fatura os vencimentos não aparecem em ordem crescente conforme sua imagem.
Vou verificar se tem algum módulo que esteja invertendo, a principio achei que poderia ser esta linha, mas acho que não...
https://github.com/akretion/l10n-brazil/blob/9ffb4bbcf643caeb93c9562fd11829cacbf38742/l10n_br_account/models/account_invoice.py#L39

Vou verificar e te retorno
